# Generated by Django 4.2 on 2023-04-27 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LMRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('likelihood', models.CharField(max_length=1)),
                ('severity', models.CharField(max_length=1)),
                ('lmra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMRA.lmra')),
            ],
        ),
    ]
