# Generated by Django 4.2 on 2023-05-05 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMRA', '0003_rename_title_lmra_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='likelihood',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='severity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
