# Generated by Django 4.2 on 2023-05-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unsafe_condition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsafecondition',
            name='name',
        ),
    ]
